- name: Ensure hostname set correctly
  hostname:
    name: "{{ controller_fqdn }}"
    use: systemd

- name: Ensure self resolvable through /etc/hosts
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} OPENFLIGHT IPA HOST ENTRY - DO NOT TOUCH"
    block: |
      {{ controller_ip }}    {{ controller_fqdn }} {{ controller_name}}.{{ site_name }} {{ controller_name }}

- name: Allow IPA services through firewall
  firewalld:
    zone: public
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: true
  with_items:
    - ldap
    - ldaps
    - kerberos
    - kpasswd

- name: Allow additional IPA ports through firewall 
  firewalld:
    zone: public
    port: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: true
  with_items: 
    - 53/udp
    - 53/tcp
    - 389/tcp
    - 636/tcp
    - 88/tcp
    - 88/udp
    - 464/tcp
    - 464/udp

- name: Install IPA server
  command: "ipa-server-install -a {{ secure_admin_password }} --hostname {{ controller_fqdn }} --ip-address={{ controller_ip }} -r {{ realm }} -p {{ secure_admin_password }} -n {{ site_name }}.{{ domain }} --no-ntp --setup-dns --forwarder={{ dns_forwarder }} --reverse-zone={{ reverse_zone }} --ssh-trust-dns --unattended"

- name: Set HBAC rules
  ipa_hbacrule:
    name: allow_all
    state: disabled
    ipa_pass: "{{ secure_admin_password }}"

- name: Create bin directory if not exists
  file:
    path: /root/bin/
    state: directory
    owner: root
    group: root

- name: Create SSH key for cluster test users
  openssh_keypair:
    path: "~/.ssh/id_ipatestuser"
    type: rsa
    size: 4096
    state: present
    force: no

- name: Read SSH pub key for cluster test users
  set_fact:
    cluster_test_user_pub_key: "{{lookup('file', '~/.ssh/id_ipatestuser.pub') }}"

- name: Install command for adding cluster to IPA
  template: 
    src: ipa-add-cluster.sh
    dest: /root/bin/ipa-add-cluster

- name: Install host-add script
  template:
    src: ipa-add-host.sh
    dest: /root/bin/ipa-add-host
